ALTER TABLE customer_referrals DISABLE ROW LEVEL SECURITY;
ALTER TABLE referral_rewards DISABLE ROW LEVEL SECURITY;
ALTER TABLE referral_timeline DISABLE ROW LEVEL SECURITY;
ALTER TABLE referral_audit_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE referral_campaigns DISABLE ROW LEVEL SECURITY;
ALTER TABLE referral_analytics DISABLE ROW LEVEL SECURITY;
ALTER TABLE referral_reversals DISABLE ROW LEVEL SECURITY;
ALTER TABLE referral_event_history DISABLE ROW LEVEL SECURITY;
